/* Thin wrapper around the bundled `flyctl` CLI. We shell out rather than
 * speaking to the Machines API directly because flyctl handles:
 *   - source upload + remote build (no Docker daemon needed in our runtime)
 *   - image registry push
 *   - app create-if-missing
 *   - rolling release with healthcheck wait
 * All of which would be a substantial reimplementation for marginal gain. */

import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FLYCTL = process.env.FLYCTL_PATH ?? 'flyctl';

export interface FlyOrg {
  org: string;
  token: string;
  defaultRegion: string;
}

export function readFlyEnv(): FlyOrg {
  const token = process.env.FLY_API_TOKEN;
  const org = process.env.FLY_ORG;
  if (!token) throw new Error('FLY_API_TOKEN is not set');
  if (!org) throw new Error('FLY_ORG is not set (e.g. "inzone-games")');
  return { token, org, defaultRegion: process.env.FLY_REGION ?? 'iad' };
}

/** Generates a fly.toml at `cwd/fly.toml` with InZone's sensible defaults.
 *  We only generate one if the dev didn't ship their own — devs who need
 *  finer control (custom regions, multiple processes, custom healthchecks)
 *  can override by including a fly.toml in their zip. */
export function writeDefaultFlyToml(args: {
  cwd: string;
  appName: string;
  region: string;
  internalPort: number;
}): void {
  const body = `# Generated by InZone Studio.
app = "${args.appName}"
primary_region = "${args.region}"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = ${args.internalPort}
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
`;
  writeFileSync(join(args.cwd, 'fly.toml'), body, 'utf8');
}

export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

/** Spawns a flyctl subprocess with `FLY_API_TOKEN` injected. `onLine` fires
 *  for each stdout/stderr line so the caller can stream logs to Firestore.
 *  Resolves once the process exits, regardless of exit code. */
export function runFlyctl(args: {
  argv: string[];
  cwd?: string;
  env?: Record<string, string>;
  onLine?: (stream: 'stdout' | 'stderr', line: string) => void;
  timeoutMs?: number;
}): Promise<RunResult> {
  return new Promise((resolve, reject) => {
    const proc = spawn(FLYCTL, args.argv, {
      cwd: args.cwd,
      env: {
        ...process.env,
        ...args.env,
        FLY_API_TOKEN: process.env.FLY_API_TOKEN ?? '',
      },
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    let stdoutBuf = '';
    let stderrBuf = '';

    const onChunk = (stream: 'stdout' | 'stderr', chunk: Buffer) => {
      const text = chunk.toString('utf8');
      if (stream === 'stdout') { stdout += text; stdoutBuf += text; }
      else                     { stderr += text; stderrBuf += text; }
      // Flush complete lines.
      let buf = stream === 'stdout' ? stdoutBuf : stderrBuf;
      let idx: number;
      while ((idx = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, idx).replace(/\r$/, '');
        buf = buf.slice(idx + 1);
        if (line) args.onLine?.(stream, line);
      }
      if (stream === 'stdout') stdoutBuf = buf;
      else                     stderrBuf = buf;
    };

    proc.stdout.on('data', (c) => onChunk('stdout', c));
    proc.stderr.on('data', (c) => onChunk('stderr', c));

    const timeout = args.timeoutMs ?? 10 * 60 * 1000;
    const timer = setTimeout(() => {
      proc.kill('SIGKILL');
      reject(new Error(`flyctl ${args.argv.join(' ')} timed out after ${timeout} ms`));
    }, timeout);

    proc.on('error', (err) => { clearTimeout(timer); reject(err); });
    proc.on('close', (code) => { clearTimeout(timer); resolve({ code: code ?? -1, stdout, stderr }); });
  });
}

/** Returns true if the Fly app already exists in our org. */
export async function appExists(appName: string): Promise<boolean> {
  const res = await runFlyctl({ argv: ['apps', 'show', appName, '--json'] });
  return res.code === 0;
}

export async function createApp(appName: string, org: string): Promise<void> {
  const res = await runFlyctl({
    argv: ['apps', 'create', appName, '--org', org],
  });
  if (res.code !== 0) {
    throw new Error(`flyctl apps create failed: ${res.stderr.trim() || res.stdout.trim()}`);
  }
}

/** Run `flyctl deploy --remote-only` from cwd. The remote builder uploads
 *  the source, builds the image, and rolls out machines. We surface logs
 *  line-by-line via onLine. */
export async function deployApp(args: {
  cwd: string;
  appName: string;
  onLine: (stream: 'stdout' | 'stderr', line: string) => void;
}): Promise<void> {
  const res = await runFlyctl({
    argv: [
      'deploy',
      '--remote-only',
      '--app', args.appName,
      '--yes',
    ],
    cwd: args.cwd,
    onLine: args.onLine,
    timeoutMs: 15 * 60 * 1000, // builds can take a while on first push
  });
  if (res.code !== 0) {
    throw new Error(`flyctl deploy failed (exit ${res.code}): ${res.stderr.trim() || res.stdout.trim()}`);
  }
}

/** Public hostname Fly assigns to an app — `<app>.fly.dev`. */
export function publicHostname(appName: string): string {
  return `${appName}.fly.dev`;
}

export function publicWss(appName: string): string {
  return `wss://${publicHostname(appName)}`;
}

/** Reads the first `EXPOSE <port>` from a Dockerfile, if any. We use this when
 *  generating a fly.toml so the machine routes to the port the dev's image
 *  actually listens on (e.g. BrowserQuest binds 8000) instead of blindly
 *  assuming DEFAULT_PORT — a mismatch means Fly proxies to a dead port and the
 *  game's WebSocket never connects. Returns null when no EXPOSE is present. */
export function parseExposedPort(dockerfilePath: string): number | null {
  let text: string;
  try {
    text = readFileSync(dockerfilePath, 'utf8');
  } catch {
    return null; // no/unreadable Dockerfile — caller falls back to default
  }
  // EXPOSE may carry a /tcp suffix or list several ports; take the first.
  const m = text.match(/^\s*EXPOSE\s+(\d+)/im);
  if (m) {
    const port = parseInt(m[1], 10);
    if (Number.isFinite(port) && port > 0) return port;
  }
  return null;
}

/** Force the `app = "…"` line in a shipped fly.toml to `appName`. flyctl's
 *  `--app` flag already wins over the file at deploy time, but keeping the file
 *  in sync prevents the stamped serverUrl (publicWss(appName)) from ever
 *  diverging from where the app actually deploys, and guards against flyctl
 *  versions that reject an app-name mismatch. Inserts the line if absent. */
export function normalizeFlyTomlAppName(flyTomlPath: string, appName: string): void {
  let text: string;
  try {
    text = readFileSync(flyTomlPath, 'utf8');
  } catch {
    return;
  }
  if (/^\s*app\s*=/m.test(text)) {
    text = text.replace(/^\s*app\s*=.*$/m, `app = "${appName}"`);
  } else {
    text = `app = "${appName}"\n` + text;
  }
  writeFileSync(flyTomlPath, text, 'utf8');
}
